"""added department and Level

Revision ID: 96cdc518966f
Revises: 118cef2a93bd
Create Date: 2021-09-29 11:19:16.215672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96cdc518966f'
down_revision = '118cef2a93bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('level', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'level')
    op.drop_column('users', 'department')
    # ### end Alembic commands ###
